Repository bowtie-co/houndstooth-v2, pull requests merged in 2020-08, with the labels that each got.

#4 Feature/174285580/nav repo card styles
  src/atoms/App/LastUpdated.jsx
  src/lib/language/en.js
  src/lib/language/es.js
  src/molecules/Collection/NavLink.jsx
  src/molecules/CollectionItem/NavLink.jsx
  src/molecules/Language/Select.jsx
  src/organisms/App/Navbar.jsx
  src/organisms/Repo/Cards.jsx
  src/organisms/RepoSelect/RepoSelect.jsx
  src/organisms/RepoSelect/RepoSelectContainer.jsx
  src/organisms/RepoSelect/index.js
  src/styles/atoms/atoms.scss
  src/styles/index.scss
  src/styles/molecules/molecules.scss
  src/styles/organisms/Header.scss
  src/styles/organisms/Repo.scss
Labels: enhancement

#5 Add branch selector and query param logic
  src/ecosystems/Github/WithRepo.jsx
  src/ecosystems/Global/WithQueryParams.jsx
  src/ecosystems/Global/WithRoutes.jsx
  src/ecosystems/Global/index.js
  src/molecules/Branch/Select.jsx
  src/molecules/Branch/index.js
  src/molecules/Collection/Card.jsx
  src/molecules/Collection/NavLink.jsx
  src/molecules/CollectionItem/Card.jsx
  src/molecules/CollectionItem/NavLink.jsx
  src/molecules/Repo/Select.jsx
  src/molecules/index.js
  src/organisms/App/Navbar.jsx
  src/organisms/App/Sidebar.jsx
  src/styles/atoms/atoms.scss
  src/styles/molecules/molecules.scss
  src/styles/organisms/Header.scss
Labels: enhancement

#6 Feature/173950356/preview by deploy statuses
  package-lock.json
  package.json
  src/ecosystems/Github/WithRepoControls.jsx
  src/ecosystems/Github/WithRepos.jsx
  src/organisms/App/Navbar.jsx
Labels: enhancement

#7 Repo list pagination
  package-lock.json
  package.json
  src/atoms/App/LastUpdated.jsx
  src/atoms/BowtieLoader/Loader.jsx
  src/ecosystems/Github/WithRepos.jsx
  src/ecosystems/Global/WithLoader.jsx
  src/molecules/App/Pagination.jsx
  src/molecules/App/index.js
  src/molecules/Language/Select.jsx
  src/molecules/Repo/Select.jsx
  src/organisms/App/Navbar.jsx
  src/organisms/Repo/Cards.jsx
  src/styles/index.scss
Labels: enhancement

#9 Fix use of repos & related prop dependencies
  src/ecosystems/Github/WithRepos.jsx
  src/molecules/Repo/Select.jsx
  src/molecules/Repo/Selector.jsx
  src/molecules/Repo/index.js
  src/organisms/App/Navbar.jsx
  src/organisms/Repo/Cards.jsx
Labels: bug

#10 Improve hover/disabled styles & disable last until repos loaded
  src/molecules/App/Pagination.jsx
  src/organisms/Repo/Cards.jsx
  src/styles/index.scss
Labels: enhancement

#12 Update asset uploads (via s3)
  .env.development
  package-lock.json
  package.json
  src/molecules/Form/Field/Recursive.jsx
  src/molecules/Form/Field/Upload.jsx
Labels: enhancement

#13 Bug/174390176/translate not a function
  src/ecosystems/Global/WithApp.jsx
  src/ecosystems/Global/WithLanguage.jsx
  src/ecosystems/Global/index.js
  src/molecules/CollectionItem/Editor.jsx
  src/pages/App/Home.jsx
  src/pages/App/NotFound.jsx
  src/pages/Collection/All.jsx
  src/pages/Collection/One.jsx
  src/pages/CollectionItem/All.jsx
  src/pages/CollectionItem/One.jsx
  src/pages/Pull/All.jsx
  src/pages/Pull/One.jsx
  src/pages/Repo/All.jsx
  src/pages/Repo/One.jsx
  src/pages/User/All.jsx
  src/pages/User/One.jsx
Labels: bug, enhancement

#14 Enhance "auto fix" for errors related to saved data (local/session storage)
  src/ecosystems/Global/WithErrorBoundary.jsx
Labels: bug, enhancement

#16 Bug/174413733/noisey console warnings
  src/atoms/App/Button.jsx
  src/molecules/Form/Field/Checkbox.jsx
  src/molecules/Form/Field/Input.jsx
  src/molecules/Form/Field/Recursive.jsx
  src/molecules/Form/Field/TextArea.jsx
  src/molecules/Form/Recursive.jsx
Labels: bug, good first issue
